### ISSUE TITLE
Settings:get in blade

### ISSUE THREAD

**Issue by JFOC** [edvinaskrucas/settings#11]
Calling in blade template
`{{ Settings::get('configname') }}
`

Returning blank value.

**Comment by edvinaskrucas** [comment]
Do you have this value in storage?

**Comment by JFOC** [comment]
Yes I have the value, but it seems is related to keygenerator, since the key generator is using md5, but I am trying to get config name that are not in md5

**Comment by edvinaskrucas** [comment]
Do not use md5 key generator
