### ISSUE TITLE
Laravel version >=5.0, <=5.1 with <= 2.0.0 or with < 2.0.0

### ISSUE THREAD

**Issue by Uebix** [edvinaskrucas/settings#13]
Hello @edvinaskrucas , this is only a question...
In your readme you say:
Laravel version >=5.0, <=5.1    Package version >= 1.0.0, <= 2.0.0
Is correct **<=** 2.0.0 for Laravel 5.1 or is correct **<** 2.0.0 ?

Thanks

**Comment by edvinaskrucas** [comment]
Hey,

2.0.0 should work, if no - downgrade
