### ISSUE TITLE
unserialize error + disabled cache

### ISSUE THREAD

**Issue by tarampampam** [edvinaskrucas/settings#15]
I use this config:
```php
return [
    'default' => env('SETTINGS_DRIVER', 'database'),
    'cache' => true,
    'encryption' => false,
    'events' => true,
    'repositories' => [
        'database' => [
            'driver' => 'database',
            'connection' => env('DB_CONNECTION', 'mysql'),
            'table' => 'settings',
        ],
    ],
    'key_generator' => \Krucas\Settings\KeyGenerators\KeyGenerator::class,
    'context_serializer' => \Krucas\Settings\ContextSerializers\ContextSerializer::class,
    'value_serializer' => \Krucas\Settings\ValueSerializers\ValueSerializer::class,
    'override' => [],
];
```

And `Laravel Framework version 5.3.23`. Then I set `'cache' => false` - application crushes with message:
> ErrorException in /home/user/php/my_app/vendor/edvinaskrucas/settings/src/Krucas/Settings/ValueSerializers/ValueSerializer.php line 28:
> unserialize(): Error at offset 0 of 3 bytes (View: /home/user/php/my_app/resources/views/pages/settings/index.blade.php)

Database is clear (after `migrate:refresh`), files cache is cleared. And if I change `'cache' => true`- all works fine. Is it normal?

**Comment by tehwave** [comment]
I have this issue as well on Laravel 5.3.
