### ISSUE TITLE
Updating 'config/app.php' ServiceProvider array to register this package breaks artisan commands

### ISSUE THREAD

**Issue by sasindumendis** [edvinaskrucas/settings#2]
Gives below error with every Artisan command;

[PDOException] could not find driver

**Comment by edvinaskrucas** [comment]
It seems that you have misconfigured this package, as it could not find database driver.

**Comment by sasindumendis** [comment]
I followed the usual steps to configure the package and when I add the ServiceProvider this happens. When I remove it everything gets back to normal.

**Comment by edvinaskrucas** [comment]
Hey, I can't reproduce it, but you can try to install new version: 1.1.0
