### ISSUE TITLE
.env issue

### ISSUE THREAD

**Issue by kiwina** [edvinaskrucas/settings#4]
No1
local.ERROR: exception 'RuntimeException' with message 'No supported encrypter found. The cipher and / or key length are invalid.'
No2
local.ERROR: exception 'RuntimeException' with message 'No supported encrypter found. The cipher and / or key length are invalid.'

Once in a while i get these error one after another for some reason the .env is not being picked up and the default SomeRandomString obviously makes it all fails.

this also happens with the database settings

Once i change the app and database file no more issues

**Comment by edvinaskrucas** [comment]
Hello, this is related to Laravel encryption package, you have to set it up properly. Also after saving some settings and then changing your app key might lead you to problems, as entries will be encoded with different keys.
