### ISSUE TITLE
Documentation: How to create a Repository Driver

### ISSUE THREAD

**Issue by murrant** [edvinaskrucas/settings#9]
I'd like to create a custom Repository Driver for my app, but I'm not quite getting it all put together.

Can you give some instructions on what needs to be done to add a custom driver?

**Comment by murrant** [comment]
It would be great if you provided an extend function like Laravel does for several of it's providers.

https://laravel.com/api/5.0/Illuminate/Support/Manager.html#method_extend

**Comment by murrant** [comment]
It seems as though extend is not defined on Settings.  May need some code to allow this...

**Comment by edvinaskrucas** [comment]
Hello, settings package supports custom repositories, please take a look at https://github.com/edvinaskrucas/settings/blob/master/src/Krucas/Settings/Factory.php it has all methods for extending it.

**Comment by murrant** [comment]
Sorry, I'm kind of new to Laravel and I couldn't get it figured out.  I just ended up creating my own settings class.  Thanks.
